---
output: html
html-table-processing: none
---

# Code Along in R: Coffee Table

Setting up.

```{r}
library(gt)
library(tidyverse)
```

Importing the data.

```{r}
coffee_sales <- readr::read_csv("data/coffee-sales.csv")

coffee_sales
```

`gt()`

```{r}
gt_tbl_1 <- gt(coffee_sales) # <- what do we introduce to gt()?

gt_tbl_1
```

## Adding Structure to the Table

`tab_header()`

```{r}
gt_tbl_2 <- gt_tbl_1 |> tab_header(title = "Sales of Coffee Equipment")

gt_tbl_2
```

`tab_spanner()`

```{r}
# We want two spanners in our table
gt_tbl_3 <-
    gt_tbl_2 |>
    tab_spanner(label = "Revenue", columns = starts_with("revenue"))
    # tab_spanner(...) # <- ?

gt_tbl_3
```

`cols_label()`

```{r}
# We want to make `icon` blank and re-label all other columns
gt_tbl_4 <-
    gt_tbl_3 |>
    cols_label(
        product = "Product",
        revenue_dollars = "Amount",
        revenue_pct = "Percent",
        monthly_sales = "Monthly Sales"
    )

gt_tbl_4
```

## Formatting Values Within the Table Body

`fmt_currency()`

```{r}
gt_tbl_5 <- 
    gt_tbl_4 |>
    fmt_currency(
        columns = ...("..."), # <- Need to select columns here
        use_subunits = FALSE
    )

gt_tbl_5
```

`fmt_percent()`

```{r}
gt_tbl_6 <-
    gt_tbl_5 |>
    fmt_percent(
        columns = ends_with("..."), # <- What string do we use?
        decimals = 0
    )

gt_tbl_6
```

## Styling the Table

`.tab_style()` - 1

```{r}
gt_tbl_7 <-
    gt_tbl_6 |>
    tab_style(
        style = cell_fill(color = "aliceblue"),
        locations = cells_body(columns = ...("revenue")) # <- ?
    )

gt_tbl_7
```

`.tab_style()` - 2

```{r}
gt_tbl_8 <-
    gt_tbl_7 |>
    tab_style(
        style = ...(color = "papayawhip"), # <- fn for specifying a fill?
        locations = cells_body(columns = ...("profit"))  # <- ?
    )

gt_tbl_8
```

`.tab_style()` - 3

```{r}
gt_tbl_9 <-
    gt_tbl_8 |>
    tab_style(
        style = cell_text(weight = "bold"),
        locations = cells_body(rows = product == "...") # <- What str?
    )

gt_tbl_9
```

## Adding a Column of Nanoplots

`cols_nanoplot()`

```{r}
gt_tbl_10 <-
    gt_tbl_9 |>
    cols_nanoplot(
        columns = monthly_sales, 
        plot_type = "bar",
        new_col_name = "nanoplots",
        new_col_label = "Monthly Revenue" 
    )

gt_tbl_10
```

## Adding Images to the Table

`fmt_image()`

```{r}
gt_tbl_11 <-
    gt_tbl_10 |>
    fmt_image(
        columns = icon,
        path = "img/"
    )

gt_tbl_11
```

## Making Some Final Tweaks

`sub_missing()`

```{r}
gt_tbl_12 <- gt_tbl_11 |> sub_missing(missing_text = "...") # <- How do we replace with blanks?

gt_tbl_12
```
