---
output: html
html-table-processing: none
---

# Code Along in R: Reactions Table

## Start

Setting up.

```{r}
library(gt)
library(tidyverse)
```

Transforming the data.

```{r}
reactions_mini <-
  reactions |>
  dplyr::filter(cmpd_type == "mercaptan") |>
  dplyr::select(cmpd_name, cmpd_formula, OH_k298, O3_k298, Cl_k298, NO3_k298)

reactions_mini
```

`gt()`

```{r}
gt_tbl_1 <- gt(______, rowname_col="cmpd_name") # <- what do we introduce to gt()?

gt_tbl_1
```

## Adding Structure to the Table

`tab_header()`

```{r}
gt_tbl_2 <-
    gt_tbl_1 |>
    tab_header(
        title = md("Gas-phase reactions of selected **mercaptan** compounds")
    )

gt_tbl_2
```

`tab_spanner()`

```{r}
gt_tbl_3 <-
    gt_tbl_2 |>
    tab_spanner(
        columns = ends_with("______"), # <- which columns have the numerical data?
        label = md(
            "Reaction Rate Constant (298 K),<br>{{cm^3 molecules^–1 s^–1}}"
        )
    )

gt_tbl_3
```

`cols_label()`

```{r}
gt_tbl_4 <-
    gt_tbl_3 |>
    cols_label(
        cmpd_formula = "",
        OH_k298 = "OH",
        O3_k298 = "{{%O3%}}",
        NO3_k298 = "{{%NO3%}}",
        Cl_k298 = "______"
    )

gt_tbl_4
```

## Formatting Values Within the Table Body

`fmt_chem()`

```{r}
gt_tbl_5 <- gt_tbl_4 |> fmt_chem(columns = "______") # <- which column has chem stuff?

gt_tbl_5
```

`fmt_scientific()`

```{r}
gt_tbl_6 <- gt_tbl_5 |> fmt_scientific(columns = ends_with("______")) # <- ?

gt_tbl_6
```

`sub_missing()`

```{r}
gt_tbl_7 <- gt_tbl_6 |> sub_missing()

gt_tbl_7
```

`cols_hide()`

```{r}
gt_tbl_8 <- gt_tbl_7 |> cols_hide(columns = "______") # <- which column has nothing?

gt_tbl_8
```

## Styling the Table

`opt_stylize()`

```{r}
gt_tbl_9 <- gt_tbl_8 |> opt_stylize(style = 1, color = "blue")

gt_tbl_9
```

## Making Some Final Tweaks

`opt_table_font()`

```{r}
gt_tbl_10 <- gt_tbl_9 |> opt_table_font(stack = "humanist")

gt_tbl_10
```

`opt_horizontal_padding()`

```{r}
gt_tbl_11 <- gt_tbl_10 |> opt_horizontal_padding(scale = 3)

gt_tbl_11
```
