---
output: html
html-table-processing: none
---

# Code Along in R: Power Generation Table

## Start

Setting up.

```{r}
library(gt)
library(tidyverse)
```

Importing the data.

```{r}
power_generation <- readr::read_csv("data/power-generation.csv")

power_generation
```

```{r}
gt_tbl_1 <- gt(power_generation)

gt_tbl_1
```

## Adding Structure to the Table

`tab_header()` + `md()`

```{r}
gt_tbl_2 <-
    gt_tbl_1 |>
    tab_header(
        title = md("2023 Mean **Carbon Intensity** (gCO2eq/kWh) and **Power Consumption** Breakdown (%)")
    )

gt_tbl_2
```

`tab_source_note()` + `md()`

```{r}
gt_tbl_3 <-
    gt_tbl_2 |>
    tab_source_note(
        md("
**Source**: api.electricitymap.org | 
**Methodology**: https://www.electricitymaps.com/methodology.
Some emissions factors are based on IPCC 2014 defaults, while some are
based on more accurate regional factors.
<br>All zones are publicly available on the *Carbon intensity and emission factors* tab via Google docs link
"
        )
    )

gt_tbl_3
```

`cols_width()`

```{r}
gt_tbl_4 <-
    gt_tbl_3 |>
    cols_width(
        Zone ~ "120px",
        everything() ~ "85px"
    ) 

gt_tbl_4
```

## Formatting Values Within the Table Body

`fmt_percent()`

```{r}
gt_tbl_5 <-
    gt_tbl_4 |>
    fmt_percent(
        columns = -`CO2 Intensity`,
        decimals = 1
    )

gt_tbl_5
```

`fmt_integer()`

```{r}
gt_tbl_6 <- gt_tbl_5 |> fmt_integer(columns=`CO2 Intensity`)

gt_tbl_6
```

## Styling the Table

`data_color()` - 1

```{r}
gt_tbl_7 <-
    gt_tbl_6 |>
    data_color(
        columns = `CO2 Intensity`,
        palette = c(
            "#00A600", "#E6E600", "#E8C32E",
            "#D69C4E", "#Dc863B", "sienna",
            "sienna4", "tomato4", "brown"
        ),
        domain = c(0, 900)
    )

gt_tbl_7
```

`data_color()` - 2

```{r}
gt_tbl_8 <-
    gt_tbl_7 |>
    data_color(
        columns = c(Hydro, Nuclear, Wind, Solar, Geothermal),
        palette = c("#00A600", "chartreuse3", "chartreuse4", "snow"),
        domain = c(0, 1),
        reverse = TRUE
    )

gt_tbl_8
```

`data_color()` - 3

```{r}
gt_tbl_9 <-
    gt_tbl_8 |>
    data_color(
        columns = Biomass,
        palette = c("snow", "#EEC900", "#E8C32E", "#D69C4E"),
        domain = c(0, 0.3)
  )

gt_tbl_9
```

`data_color()` - 4

```{r}
gt_tbl_10 <-
    gt_tbl_9 |>
    data_color(
        columns = Gas:Oil,
        palette = c("tomato4", "sienna4", "#D69C4E", "#Dc863B", "snow"),
        domain = c(0, 1),
        reverse = TRUE
    )

gt_tbl_10
```

`tab_style()`

```{r}
gt_tbl_11 <-
    gt_tbl_10 |>
    tab_style(
        style = cell_fill(color = "snow"),
        locations = cells_body(columns = c(Zone, Unknown:`Battery Discharge`))
    )

gt_tbl_11
```

## Making Some Final Tweaks

`cols_align()` - 1

```{r}
gt_tbl_12 <- gt_tbl_11 |> cols_align(align = "center")

gt_tbl_12
```

`cols_align()` - 2

```{r}
gt_tbl_13 <- gt_tbl_12 |> cols_align(align = "left", columns = Zone)

gt_tbl_13
```

`opt_table_font()`

```{r}
gt_tbl_14 <- gt_tbl_13 |> opt_table_font(stack = "humanist")

gt_tbl_14
```

`tab_options()`

```{r}
gt_tbl_15 <-
    gt_tbl_14 |>
    tab_options(
        source_notes.font.size = "x-small",
        source_notes.padding = "3px",
        data_row.padding = "1px",
        heading.background.color = "antiquewhite",
        source_notes.background.color = "antiquewhite",
        column_labels.background.color = "antiquewhite",
        table.background.color = "snow",
        data_row.padding.horizontal = "3px",
        column_labels.padding.horizontal = "0px"
    )

gt_tbl_15
```
