---
format: revealjs
---

## Making Tables with gt and Great Tables

Instructors: Michael Chow and Rich Iannone

<br>

### Course Materials

All workshop content is available at:

https://github.com/posit-conf-2024/tables

<br>

We also have the workshop materials in a Posit Cloud instance:

--Public Link for Posit Cloud Materials--

## Discord

Join the gt / Great Tables Discord to ask questions during the Workshop:

<https://discord.com/invite/Ux7nrcXHVV>

---


### Structure of Workshop

There are four 1.5 hour blocks and in each we will go through this basic sequence:

- **slides** to get a basic understanding of new concepts
- **code-along** to further immerse ourselves in the material
- **exercise** to work semi-independently and better figure things out

## Schedule

Here is how the day is planned:

| Time	        | Activity                        |
|---------------|---------------------------------|
| 09:00 - 10:30 | Session 1: Coffee Table         |
| 10:30 - 11:00	| Coffee break                    |
| 11:00 - 12:30	| Session 2: Reactions Table      |
| 12:30 - 13:30	| Lunch break                     |
| 13:30 - 15:00	| Session 3: Power Gen Table      |
| 15:00 - 15:30	| Coffee break                    |
| 15:30 - 17:00	| Session 4: Interactive Tables   |
